# Generated by Django 5.0.2 on 2024-03-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjOne', models.CharField(max_length=100)),
                ('nomeEmprOne', models.CharField(max_length=100)),
                ('endOne', models.CharField(max_length=100)),
                ('cnpjTwo', models.CharField(max_length=100)),
                ('nomeEmprTwo', models.CharField(max_length=100)),
                ('endTwo', models.CharField(max_length=100)),
                ('valorNf', models.CharField(max_length=100)),
                ('pesoNf', models.CharField(max_length=100)),
                ('quantNf', models.CharField(max_length=100)),
                ('valorCota', models.CharField(max_length=100)),
            ],
        ),
    ]
